USE Books
Go

CREATE TABLE BOOK(BOOK_ID INT PRIMARY KEY, Name VARCHAR (150), INVENTORY_ID INT);
CREATE TABLE AUTHOR(AUTHOR_ID INT PRIMARY KEY, AUTH_NAME VARCHAR(150), BOOK_ID INT REFERENCES BOOK(BOOK_ID));
CREATE TABLE AUTHORS(AUTHOR_ID INT REFERENCES AUTHOR(AUTHOR_ID), BOOK_TITLE VARCHAR(150));

